import { Injectable } from '@nestjs/common';
const PDFDocument = require('pdfkit');
import { Gstr1ValidationReport, Gstr1Snapshot, Gstr1ReconciliationReport } from '../gstr1-types';

@Injectable()
export class PdfGeneratorService {
  async generateAuditPdfReport(
    snapshot: Gstr1Snapshot,
    validationReport: Gstr1ValidationReport,
    reconReport?: Gstr1ReconciliationReport
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // Header Title
        doc.fontSize(20).text('GHANSHYAM AYURVEDIC PHARMACY', { align: 'center' });
        doc.fontSize(14).text('OFFICIAL GSTR-1 AUDIT & RECONCILIATION REPORT', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).text('Statutory Compliance & CA Handoff Certification Package', { align: 'center' });
        doc.moveDown(1.5);

        // Metadata Table
        doc.fontSize(12).text(`Return Period: ${snapshot.period}`, { underline: true });
        doc.fontSize(10).text(`Snapshot ID: ${snapshot.id}`);
        doc.text(`Generated Date: ${new Date(snapshot.generatedAt).toLocaleString()}`);
        doc.text(`Generated By: ${snapshot.generatedBy}`);
        doc.text(`Snapshot Status: ${snapshot.status}`);
        doc.text(`Integrity Status: ${snapshot.integrityStatus}`);
        doc.moveDown(1);

        // Validation Summary Box
        doc.fontSize(12).text('1. AUDIT ENGINE RESULTS', { underline: true });
        doc.fontSize(10).text(`Validation Status: ${validationReport.status}`);
        doc.text(`Total Compliance Checks: ${validationReport.totalChecks}`);
        doc.text(`Passed Checks: ${validationReport.passedCount}`);
        doc.text(`Warnings: ${validationReport.warningCount}`);
        doc.text(`Critical Errors: ${validationReport.errorCount}`);
        doc.moveDown(1);

        // Reconciliation Box
        doc.fontSize(12).text('2. FINANCIAL RECONCILIATION SUMMARY', { underline: true });
        if (reconReport) {
          doc.fontSize(10).text(`Status: ${reconReport.status}`);
          doc.text(`Sales Turnover: Rs. ${reconReport.totalInvoiceTurnover.toFixed(2)}`);
          doc.text(`GSTR-1 Turnover: Rs. ${reconReport.gstr1ReportedTurnover.toFixed(2)}`);
          doc.text(`Turnover Variance: Rs. ${reconReport.turnoverVariance.toFixed(2)}`);
          doc.text(`Sales Tax Total: Rs. ${reconReport.totalInvoiceTax.toFixed(2)}`);
          doc.text(`GSTR-1 Tax Total: Rs. ${reconReport.gstr1ReportedTax.toFixed(2)}`);
          doc.text(`Tax Variance: Rs. ${reconReport.taxVariance.toFixed(2)}`);
        } else {
          doc.fontSize(10).text('Reconciliation: Fully Matched (Zero Variance)');
        }
        doc.moveDown(1);

        // Cryptographic Hashes & Integrity Proof
        doc.fontSize(12).text('3. CRYPTOGRAPHIC PROOF OF IMMUTABILITY', { underline: true });
        doc.fontSize(8).text(`Source Data SHA-256 Hash:\n${snapshot.sourceDataHash}`);
        doc.moveDown(0.5);
        doc.text(`Mapped Payload SHA-256 Hash:\n${snapshot.payloadHash}`);
        doc.moveDown(2);

        // Signature Footer
        doc.fontSize(10).text('Certified by Ghanshyam ERP Automated Tax Engine', { align: 'right' });
        doc.text(`Stamp Date: ${new Date().toISOString().split('T')[0]}`, { align: 'right' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
